spring:
  mail:
    host: smtp.qq.com
    username: 2844797705@qq.com
    # QQ 邮箱的授权码 qphsyavkjmoddfii
    password: ysaangqtssrpdedi
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
  servlet:
    multipart:
      # 开启multipart上传功能
      enabled: true
      # 最大文件大小
      max-file-size: 200MB
      # 最大请求大小
      max-request-size: 215MB
server:
  port: 80